# Generated by Django 5.2.2 on 2025-06-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='number_of_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Likes'),
        ),
    ]
