# Generated by Django 5.2.2 on 2025-06-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_user_alter_note_number_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Is Public'),
        ),
    ]
