# Generated by Django 5.2.2 on 2025-06-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='public',
            new_name='is_public',
        ),
    ]
